import 'package:llms/helpers/helper.dart';
import 'package:llms/helpers/sql_manager.dart';

List<Map> getItems() {
  return [
    {
      "id": 0,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "20,000",
      "mid_left_text": "NGOUOGHE Junior",
      "bottom_left_text": "654370303",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "rent, electricity, fo...",
      "bottom_right_type": "normal",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 1,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "12,000",
      "mid_left_text": "Joe Clinton",
      "bottom_left_text": "657897999",
      "top_left_small_text": "FCFA",
      "top_right_text": "05-05-2023 at 17:22",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 2,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "17,500",
      "mid_left_text": "Morientes Arthur",
      "bottom_left_text": "654222343",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 3,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "2,000",
      "mid_left_text": "Harry Potter",
      "bottom_left_text": "654090111",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "rent, electricity, fo...",
      "bottom_right_type": "normal",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 4,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "20,500",
      "mid_left_text": "Paol Le Guene",
      "bottom_left_text": "698776022",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/pen_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 5,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "2,000,000",
      "mid_left_text": "Paris Hilton",
      "bottom_left_text": "675435656",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 6,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "12,500",
      "mid_left_text": "Tiddy Hilary",
      "bottom_left_text": "654370303",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    },
    {
      "id": 7,
      "left_icon_width_fraction": 0.15,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "2,000,000",
      "mid_left_text": "NGOUOGHE Junior",
      "bottom_left_text": "654370303",
      "top_left_small_text": "FCFA",
      "top_right_text": "07-05-2023 at 12:35",
      "bottom_right_text": "uncategorized",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "17",
      "left_image_path": "/message_icon.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": false,
      "max_lines_mid_left_text": 1,
      "mid_left_text_is_half_screen": false
    }
  ];
}

Future<List<Map>> getTenantItems() async {
  List<Map> tenantItems = await SqlManager.getItems("Tenant");
  List<Map> displayMaps = getTenantDisplayMapsFromObjectMaps(tenantItems);
  print(displayMaps);
  return displayMaps;
}

List<Map> getServiceItems() {
  double left_icon_width_fraction = 0.15;
  return [
    {
      "id": 0,
      "left_icon_width_fraction": left_icon_width_fraction,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "Rent",
      "mid_left_text": "Monthly payment for the tenant to stay ...",
      "bottom_left_text": "",
      "top_left_small_text": "",
      "top_right_text": "",
      "bottom_right_text": "1 month",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "15",
      "left_image_path": "/serviceDefaultPic.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": true,
      "max_lines_mid_left_text": 2,
      "mid_left_text_is_half_screen": true
    },
    {
      "id": 1,
      "left_icon_width_fraction": left_icon_width_fraction,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "Water Bills",
      "mid_left_text": "Monthly payment for access to water",
      "bottom_left_text": "",
      "top_left_small_text": "",
      "top_right_text": "",
      "bottom_right_text": "1 month",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "15",
      "left_image_path": "/serviceDefaultPic.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": true,
      "max_lines_mid_left_text": 2,
      "mid_left_text_is_half_screen": true
    },
    {
      "id": 2,
      "left_icon_width_fraction": left_icon_width_fraction,
      "on_delete": null,
      "on_edit": null,
      "top_left_text": "Electricity Bills",
      "mid_left_text": "Monthly payment for access to electricity",
      "bottom_left_text": "",
      "top_left_small_text": "",
      "top_right_text": "",
      "bottom_right_text": "1 month",
      "bottom_right_type": "highlighted",
      "top_left_font_size": "15",
      "left_image_path": "/serviceDefaultPic.png",
      "left_image_type": "asset",
      "hide_bottom_left_text": true,
      "max_lines_mid_left_text": 2,
      "mid_left_text_is_half_screen": true
    },
    // {
    //   "id": 3,
    //   "left_icon_width_fraction": left_icon_width_fraction,
    //   "on_delete": null,
    //   "on_edit": null,
    //   "top_left_text": "Rent",
    //   "mid_left_text": "Monthly payment for the tenant to stay ...",
    //   "bottom_left_text": "",
    //   "top_left_small_text": "",
    //   "top_right_text": "",
    //   "bottom_right_text": "1 month",
    //   "bottom_right_type": "highlighted",
    //   "top_left_font_size": "15",
    //   "left_image_path": "/serviceDefaultPic.png",
    //   "left_image_type": "asset",
    //   "hide_bottom_left_text": true,
    //   "max_lines_mid_left_text": 2,
    //   "mid_left_text_is_half_screen": true
    // },
    // {
    //   "id": 4,
    //   "left_icon_width_fraction": left_icon_width_fraction,
    //   "on_delete": null,
    //   "on_edit": null,
    //   "top_left_text": "Rent",
    //   "mid_left_text": "Monthly payment for the tenant to stay ...",
    //   "bottom_left_text": "",
    //   "top_left_small_text": "",
    //   "top_right_text": "",
    //   "bottom_right_text": "1 month",
    //   "bottom_right_type": "highlighted",
    //   "top_left_font_size": "15",
    //   "left_image_path": "/serviceDefaultPic.png",
    //   "left_image_type": "asset",
    //   "hide_bottom_left_text": true,
    //   "max_lines_mid_left_text": 2,
    //   "mid_left_text_is_half_screen": true
    // },
    // {
    //   "id": 5,
    //   "left_icon_width_fraction": left_icon_width_fraction,
    //   "on_delete": null,
    //   "on_edit": null,
    //   "top_left_text": "Rent",
    //   "mid_left_text": "Monthly payment for the tenant to stay ...",
    //   "bottom_left_text": "",
    //   "top_left_small_text": "",
    //   "top_right_text": "",
    //   "bottom_right_text": "1 month",
    //   "bottom_right_type": "highlighted",
    //   "top_left_font_size": "15",
    //   "left_image_path": "/serviceDefaultPic.png",
    //   "left_image_type": "asset",
    //   "hide_bottom_left_text": true,
    //   "max_lines_mid_left_text": 2,
    //   "mid_left_text_is_half_screen": true
    // },
    // {
    //   "id": 6,
    //   "left_icon_width_fraction": left_icon_width_fraction,
    //   "on_delete": null,
    //   "on_edit": null,
    //   "top_left_text": "Rent",
    //   "mid_left_text": "Monthly payment for the tenant to stay ...",
    //   "bottom_left_text": "",
    //   "top_left_small_text": "",
    //   "top_right_text": "",
    //   "bottom_right_text": "1 month",
    //   "bottom_right_type": "highlighted",
    //   "top_left_font_size": "15",
    //   "left_image_path": "/serviceDefaultPic.png",
    //   "left_image_type": "asset",
    //   "hide_bottom_left_text": true,
    //   "max_lines_mid_left_text": 2,
    //   "mid_left_text_is_half_screen": true
    // },
    // {
    //   "id": 7,
    //   "left_icon_width_fraction": left_icon_width_fraction,
    //   "on_delete": null,
    //   "on_edit": null,
    //   "top_left_text": "Rent",
    //   "mid_left_text": "Monthly payment for the tenant to stay ...",
    //   "bottom_left_text": "",
    //   "top_left_small_text": "",
    //   "top_right_text": "",
    //   "bottom_right_text": "1 month",
    //   "bottom_right_type": "highlighted",
    //   "top_left_font_size": "15",
    //   "left_image_path": "/serviceDefaultPic.png",
    //   "left_image_type": "asset",
    //   "hide_bottom_left_text": true,
    //   "max_lines_mid_left_text": 2,
    //   "mid_left_text_is_half_screen": true
    // },
  ];
}

List<Map> getTenantDisplayMapsFromObjectMaps(List<Map> objectMaps) {
  List<Map> tenantDisplayMaps = [];
  for (Map objectMap in objectMaps) {
    tenantDisplayMaps.add(getTenantDisplayMapFromObjectMap(objectMap));
  }
  return tenantDisplayMaps;
}

Map getTenantDisplayMapFromObjectMap(Map objectMap) {
  double left_icon_width_fraction = 0.15;
  return {
    "id": objectMap["id"],
    "left_icon_width_fraction": left_icon_width_fraction,
    "on_delete": null,
    "on_edit": null,
    "top_left_text": objectMap["fullname"],
    "mid_left_text": objectMap["phone_number"],
    "bottom_left_text": objectMap["job"],
    "top_left_small_text": "",
    "top_right_text": "",
    "bottom_right_text": "${Helper.getDisplayAmount(objectMap["rent"])} / mo",
    "bottom_right_type": "highlighted",
    "top_left_font_size": "15",
    "left_image_path": "/defaultProfileCardPic.png",
    "left_image_type": "asset",
    "hide_bottom_left_text": false,
    "max_lines_mid_left_text": 1,
    "mid_left_text_is_half_screen": false
  };
}
